Rewrite RFC report
NixOS/rfc-steering-committee pull request #122
Opened 2023-09-04 15:57 UTC by kevincox

This has a few key features:
1. Ensures that RFCs can't fall through the cracks with funny label combinations. All open PRs will be included somewhere in the report.
2. Automatically pull nomination-related comments for PRs that are open for nominations.
3. Show labels (other than those implied by the category).
4. Update the next meeting timestamp automatically.

2023-09-04 18:09 UTC, infinisil commented on rfc-report.py
> +			m = NOMINATION_RE.search(line)
This should be ensured to match case-insensitively

2023-09-06 13:06 UTC, infinisil requested changes

2023-09-06 13:06 UTC, infinisil commented on rfc-report.py
> +#!nix-shell -i python3 -p hub
```suggestion
#!nix-shell -i python3 -p hub python3
```

2023-09-06 18:10 UTC, infinisil requested changes

2023-09-06 18:37 UTC, kevincox commented on rfc-report.py
> +MARKDOWN_NESTING_RE = re.compile(r"([[])")
It's not surprising that it works. Characters have different meanings inside `[]`. But I do see the warning so best to do what they want.

2023-09-07 15:23 UTC, infinisil approved these changes

2023-09-07 21:59 UTC, merged